### ISSUE TITLE
Lightweight dependency on MakieCore

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/VlasiatorMakie.jl#9]
Now Makie makes a standalone [MakieCore](https://makie.juliaplots.org/stable/documentation/recipes/) for building recipes. We can depend purely on that. If it works fine, we can also consider merge this package into Vlasiator.jl.

**Comment by henry2004y** [comment]
The current problem is the usage of `MakieLayout` and `UnicodeFun` for a proper display of log scale colorbar. If [this issue](https://github.com/JuliaPlots/Makie.jl/issues/1405) is fixed then I guess we can depend on `MakieCore` solely.

**Comment by TCLiuu** [comment]
But you used some slider objects like `SliderGrid` for interactively plotting, which are provide by `Makie` and do not exist in `MakieCore`.

**Comment by henry2004y** [comment]
Yeah that is a problem. The Makie recipe system is still not ideal at the moment. I imagine they will probably make this part better when we reach Makie v1.0 :)

**Comment by henry2004y** [comment]
Makie recipes currently (v0.18) only work on the plot object level and cannot modify Axis, Colorbar, etc. In the future when recipes can work on axis and figures, then it will become a true robust recipe system.
